name: flutter_guchi_memo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # cupertino_icons: ^1.0.2
  flutter_state_notifier: ^0.7.0
  freezed_annotation: ^0.14.2
  sqflite: ^2.0.0+3
  flutter_riverpod: ^0.14.0+3
  json_serializable: ^4.1.4
  audioplayers: ^0.19.1
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  build_runner: ^2.0.6
  freezed: ^0.14.2

flutter:

  uses-material-design: true

