name: flutter_guchi_memo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # cupertino_icons: ^1.0.2
  flutter_state_notifier: ^0.7.1
  
  freezed_annotation: ^1.1.0

  #riverpod
  hooks_riverpod: ^1.0.1
  flutter_hooks: ^0.18.2+1

  json_serializable: ^6.1.4

  #audioplayers
  audioplayers: ^0.20.1

  #pull_to_refresh
  pull_to_refresh: ^2.0.0

  #localDB
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2

  #package_info
  package_info_plus: ^1.3.0

  #local auth
  local_auth: ^1.1.10

  #firebse
  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/guchimemo_icon.png"

flutter:
  assets: 
    - assets/panti.mp3
    - assets/panti_big.mp3

  uses-material-design: true

